#!/bin/bash
source venv/bin/activate
flake8 lox/interpreter.py lox/lox.py lox/parser.py lox/printer.py lox/scanner.py \
&& rm -f .coverage && coverage run -m pytest --capture=sys && coverage report -m
