"""AUTOGENERATED! DO NOT EDIT! Make changes to tool/generate_ast.py instead"""
from typing import Any, Generic, Optional, TypeVar
from dataclasses import dataclass

from lox.token import Token
from lox.expr import Expr

T = TypeVar('T')
class Stmt:
    def accept(self, visitor: 'Visitor[T]') -> T: ...

@dataclass
class Expression(Stmt):
    expression: Expr

    def accept(self, visitor: 'Visitor[T]') -> T:
        return visitor.visit_expression_stmt(self)

@dataclass
class Print(Stmt):
    expression: Expr

    def accept(self, visitor: 'Visitor[T]') -> T:
        return visitor.visit_print_stmt(self)

@dataclass
class Var(Stmt):
    name: Token
    initializer: Optional[Expr]

    def accept(self, visitor: 'Visitor[T]') -> T:
        return visitor.visit_var_stmt(self)

R = TypeVar('R')
class Visitor(Generic[R]):
    def visit_expression_stmt(self, s: Expression) -> R: ...
    def visit_print_stmt(self, s: Print) -> R: ...
    def visit_var_stmt(self, s: Var) -> R: ...
