name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [3.6, 3.7, 3.8, 3.9, pypy3]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python3 -m venv venv \
          && source venv/bin/activate \
          && pip install -r requirements.dev.txt
      - name: Lint with flake8
        run: ./runlint
      - name: Test with pytest
        run: ./runtest nolint
